[project]
name = "measure-space-mcp-server"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.9.4",
    "measure-space-api>=0.1.3",
    "python-dotenv>=1.1.0",
]
